AWSTemplateFormatVersion: 2010-09-09
Description: SEC545 Create EC2 instance for day 1 labs.

MetaData:
   'AWS::Cloudformation"::Interface'
     ParameterGroups:
       - Label:
           Default: Tagging
        Parameters:
          - Owner
          - ApplicationName
Parameters:
   ApplicationName:
      Type: String
      Description: 'MyExampleApp'
      Default: ''
   Owner:
     Type: String
     Descriptio: 'Owner of the SNS Topic'
     Default: ''   


Resources:
  SNSTopic:
     Type: 'AWS::SNS::Topic'
     Properties:
       Tags:
         - Key: ApplicationName
           Value: !Ref ApplicationName
         - Key: Owner
           Value: !Ref Owner
          
